package com.eglobal.tramites.entity;
// default package
// Generated 11/01/2021 10:39:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CGiros generated by hbm2java
 */
@Entity
@Table(name = "c_giros", schema = "dbo", catalog = "Catalogos_adq")
public class CGiros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String giro;
	private String descripcion;

	public CGiros() {
	}

	public CGiros(String giro, String descripcion) {
		this.giro = giro;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "giro", unique = true, nullable = false, length = 4)
	public String getGiro() {
		return this.giro;
	}

	public void setGiro(String giro) {
		this.giro = giro;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
